name: Build and Deploy SQL Database Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Connection String
        id: connstring
        run: |
          echo "CONNECTION_STRING=Server=tcp:${{ secrets.SQL_SERVER_NAME }},1433;Initial Catalog=${{ secrets.SQL_DATABASE_NAME }};User ID=${{ secrets.SQL_USER }};Password=${{ secrets.SQL_PASSWORD }};Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" >> $GITHUB_ENV

      # Use Azure SQL Action to build and deploy the SQL project
      - name: Build and Deploy SQL Project
        uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ env.CONNECTION_STRING }}
          path: './dp3020db02.sqlproj'
          action: 'publish'
          build-arguments: '-p:Configuration=Release'
