name: Build and Deploy SQL Database Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '5.0.x'

      - name: Locate MSBuild
        id: locate-msbuild
        run: |
          $msbuildPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          echo "MSBUILD_PATH=$msbuildPath" >> $env:GITHUB_ENV

      - name: Locate sqlpackage
        id: locate-sqlpackage
        run: |
          $sqlpackagePath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.SQL.DataTierAppFramework -find sqlpackage.exe
          echo "SQLPACKAGE_PATH=$sqlpackagePath" >> $env:GITHUB_ENV

      - name: Build SQL Database Project
        working-directory: ./dp3020db02
        run: |
          & $env:MSBUILD_PATH /t:Build /p:Configuration=Release /p:TargetFrameworkVersion=v4.8 dp3020db02.sqlproj

      - name: List Build Directory
        run: dir ./dp3020db02/bin/Release

      - name: Deploy to Azure SQL Database
        run: |
          & $env:SQLPACKAGE_PATH /Action:Publish /SourceFile:./dp3020db02/bin/Release/dp3020db02.dacpac /TargetServerName:${{ secrets.SQL_SERVER_NAME }} /TargetDatabaseName:dp3020db02 /TargetUser:${{ secrets.SQL_ADMIN_USER }} /TargetPassword:${{ secrets.SQL_ADMIN_PASSWORD }}
