name: Check .NET Version

on:
  push:
    branches:
      - main

jobs:
  check-dotnet-version:
    runs-on: windows-latest
    steps:
      - name: Display .NET SDK Version
        run: |
          dotnet --info
